---
include:
  - "ffmpeg-filters-docs"
  - "lib/**/*.rb"
exclude:
  - "spec/**/*"
  - "test/**/*"
  - "vendor/**/*"
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - typecheck
  - update_errors
formatter: []
require_paths: []
max_files: 1000
